### ISSUE TITLE
Gem and Ruby 1.9 Compatibility: undefined method `join' for Enumerator

### ISSUE THREAD

**Issue by tadman** [heroku/heroku-nav#1]
A patch has been made that allows this gem to work in Ruby 1.9 but it hasn't been bundled into the latest version of the gem:

http://github.com/heroku/heroku-nav/commit/054bb7df70ee0fa9b2c6b05e2c1586872476d062

Could this be added? The gem will simply not load in 1.9.
